[package]
name = "varint"
version = "0.1.0"
authors = ["sirkibsirkib <christopher.esterhuyse@gmail.com>"]

[dependencies]
integer-encoding = "1.0.5"
itertools = "0.7.8"
serde = "1.0.69"
serde_derive = "1.0.69"
bincode = "1.0.1"